// Theme configurations for InventoriKu using CSS custom properties
export const themes = {
  blue: {
    name: 'Biru Klasik',
    variables: {
      '--theme-primary': '#3b82f6',
      '--theme-primary-hover': '#2563eb',
      '--theme-primary-light': '#eff6ff',
      '--theme-primary-lighter': '#dbeafe',
      '--theme-accent': '#3b82f6',
      '--theme-accent-hover': '#2563eb',
      '--theme-text': '#2563eb',
      '--theme-text-dark': '#1d4ed8',
      '--theme-border': '#dbeafe',
      '--theme-border-accent': '#3b82f6',
      '--theme-bg-light': '#eff6ff',
      '--theme-bg-lighter': '#dbeafe',
      '--theme-gradient-start': '#3b82f6',
      '--theme-gradient-end': '#4f46e5',
      '--theme-gradient-start-hover': '#2563eb',
      '--theme-gradient-end-hover': '#4338ca',
      '--theme-shadow': 'rgba(59, 130, 246, 0.08)',
      '--theme-shadow-hover': 'rgba(59, 130, 246, 0.15)',
    },
    primary: 'theme-primary',
    accent: 'theme-accent',
    accentHover: 'theme-accent-hover',
    light: 'theme-light',
    lighter: 'theme-lighter',
    text: 'theme-text',
    textDark: 'theme-text-dark',
    border: 'theme-border',
    borderAccent: 'theme-border-accent',
    bgLight: 'theme-bg-light',
    bgLighter: 'theme-bg-lighter',
    sidebar: 'from-theme-gradient-start to-theme-gradient-end',
    button: 'bg-gradient-to-r from-theme-gradient-start to-theme-gradient-end hover:from-theme-gradient-start-hover hover:to-theme-gradient-end-hover text-white shadow-sm shadow-theme-shadow',
    cardHeader: 'from-theme-gradient-start to-theme-gradient-end',
    shadow: 'theme-shadow',
    shadowHover: 'theme-shadow-hover',
    success: 'emerald',
    warning: 'amber',
    danger: 'red',
  },
  purple: {
    name: 'Ungu Elegan',
    variables: {
      '--theme-primary': '#8b5cf6',
      '--theme-primary-hover': '#7c3aed',
      '--theme-primary-light': '#faf5ff',
      '--theme-primary-lighter': '#f3e8ff',
      '--theme-accent': '#8b5cf6',
      '--theme-accent-hover': '#7c3aed',
      '--theme-text': '#7c3aed',
      '--theme-text-dark': '#6d28d9',
      '--theme-border': '#f3e8ff',
      '--theme-border-accent': '#8b5cf6',
      '--theme-bg-light': '#faf5ff',
      '--theme-bg-lighter': '#f3e8ff',
      '--theme-gradient-start': '#8b5cf6',
      '--theme-gradient-end': '#7c3aed',
      '--theme-gradient-start-hover': '#7c3aed',
      '--theme-gradient-end-hover': '#6d28d9',
      '--theme-shadow': 'rgba(139, 92, 246, 0.08)',
      '--theme-shadow-hover': 'rgba(139, 92, 246, 0.15)',
    },
    primary: 'theme-primary',
    accent: 'theme-accent',
    accentHover: 'theme-accent-hover',
    light: 'theme-light',
    lighter: 'theme-lighter',
    text: 'theme-text',
    textDark: 'theme-text-dark',
    border: 'theme-border',
    borderAccent: 'theme-border-accent',
    bgLight: 'theme-bg-light',
    bgLighter: 'theme-bg-lighter',
    sidebar: 'from-theme-gradient-start to-theme-gradient-end',
    button: 'bg-gradient-to-r from-theme-gradient-start to-theme-gradient-end hover:from-theme-gradient-start-hover hover:to-theme-gradient-end-hover text-white shadow-sm shadow-theme-shadow',
    cardHeader: 'from-theme-gradient-start to-theme-gradient-end',
    shadow: 'theme-shadow',
    shadowHover: 'theme-shadow-hover',
    success: 'emerald',
    warning: 'amber',
    danger: 'red',
  },
  green: {
    name: 'Hijau Segar',
    variables: {
      '--theme-primary': '#10b981',
      '--theme-primary-hover': '#059669',
      '--theme-primary-light': '#ecfdf5',
      '--theme-primary-lighter': '#d1fae5',
      '--theme-accent': '#10b981',
      '--theme-accent-hover': '#059669',
      '--theme-text': '#059669',
      '--theme-text-dark': '#047857',
      '--theme-border': '#d1fae5',
      '--theme-border-accent': '#10b981',
      '--theme-bg-light': '#ecfdf5',
      '--theme-bg-lighter': '#d1fae5',
      '--theme-gradient-start': '#10b981',
      '--theme-gradient-end': '#0d9488',
      '--theme-gradient-start-hover': '#059669',
      '--theme-gradient-end-hover': '#0f766e',
      '--theme-shadow': 'rgba(16, 185, 129, 0.08)',
      '--theme-shadow-hover': 'rgba(16, 185, 129, 0.15)',
    },
    primary: 'theme-primary',
    accent: 'theme-accent',
    accentHover: 'theme-accent-hover',
    light: 'theme-light',
    lighter: 'theme-lighter',
    text: 'theme-text',
    textDark: 'theme-text-dark',
    border: 'theme-border',
    borderAccent: 'theme-border-accent',
    bgLight: 'theme-bg-light',
    bgLighter: 'theme-bg-lighter',
    sidebar: 'from-theme-gradient-start to-theme-gradient-end',
    button: 'bg-gradient-to-r from-theme-gradient-start to-theme-gradient-end hover:from-theme-gradient-start-hover hover:to-theme-gradient-end-hover text-white shadow-sm shadow-theme-shadow',
    cardHeader: 'from-theme-gradient-start to-theme-gradient-end',
    shadow: 'theme-shadow',
    shadowHover: 'theme-shadow-hover',
    success: 'emerald',
    warning: 'amber',
    danger: 'red',
  },
  orange: {
    name: 'Oranye Hangat',
    variables: {
      '--theme-primary': '#f97316',
      '--theme-primary-hover': '#ea580c',
      '--theme-primary-light': '#fff7ed',
      '--theme-primary-lighter': '#ffedd5',
      '--theme-accent': '#f97316',
      '--theme-accent-hover': '#ea580c',
      '--theme-text': '#ea580c',
      '--theme-text-dark': '#c2410c',
      '--theme-border': '#ffedd5',
      '--theme-border-accent': '#f97316',
      '--theme-bg-light': '#fff7ed',
      '--theme-bg-lighter': '#ffedd5',
      '--theme-gradient-start': '#f97316',
      '--theme-gradient-end': '#d97706',
      '--theme-gradient-start-hover': '#ea580c',
      '--theme-gradient-end-hover': '#b45309',
      '--theme-shadow': 'rgba(249, 115, 22, 0.08)',
      '--theme-shadow-hover': 'rgba(249, 115, 22, 0.15)',
    },
    primary: 'theme-primary',
    accent: 'theme-accent',
    accentHover: 'theme-accent-hover',
    light: 'theme-light',
    lighter: 'theme-lighter',
    text: 'theme-text',
    textDark: 'theme-text-dark',
    border: 'theme-border',
    borderAccent: 'theme-border-accent',
    bgLight: 'theme-bg-light',
    bgLighter: 'theme-bg-lighter',
    sidebar: 'from-theme-gradient-start to-theme-gradient-end',
    button: 'bg-gradient-to-r from-theme-gradient-start to-theme-gradient-end hover:from-theme-gradient-start-hover hover:to-theme-gradient-end-hover text-white shadow-sm shadow-theme-shadow',
    cardHeader: 'from-theme-gradient-start to-theme-gradient-end',
    shadow: 'theme-shadow',
    shadowHover: 'theme-shadow-hover',
    success: 'emerald',
    warning: 'amber',
    danger: 'red',
  },
  pink: {
    name: 'Pink Modern',
    variables: {
      '--theme-primary': '#ec4899',
      '--theme-primary-hover': '#db2777',
      '--theme-primary-light': '#fdf2f8',
      '--theme-primary-lighter': '#fce7f3',
      '--theme-accent': '#ec4899',
      '--theme-accent-hover': '#db2777',
      '--theme-text': '#db2777',
      '--theme-text-dark': '#be185d',
      '--theme-border': '#fce7f3',
      '--theme-border-accent': '#ec4899',
      '--theme-bg-light': '#fdf2f8',
      '--theme-bg-lighter': '#fce7f3',
      '--theme-gradient-start': '#ec4899',
      '--theme-gradient-end': '#e11d48',
      '--theme-gradient-start-hover': '#db2777',
      '--theme-gradient-end-hover': '#be185d',
      '--theme-shadow': 'rgba(236, 72, 153, 0.08)',
      '--theme-shadow-hover': 'rgba(236, 72, 153, 0.15)',
    },
    primary: 'theme-primary',
    accent: 'theme-accent',
    accentHover: 'theme-accent-hover',
    light: 'theme-light',
    lighter: 'theme-lighter',
    text: 'theme-text',
    textDark: 'theme-text-dark',
    border: 'theme-border',
    borderAccent: 'theme-border-accent',
    bgLight: 'theme-bg-light',
    bgLighter: 'theme-bg-lighter',
    sidebar: 'from-theme-gradient-start to-theme-gradient-end',
    button: 'bg-gradient-to-r from-theme-gradient-start to-theme-gradient-end hover:from-theme-gradient-start-hover hover:to-theme-gradient-end-hover text-white shadow-sm shadow-theme-shadow',
    cardHeader: 'from-theme-gradient-start to-theme-gradient-end',
    shadow: 'theme-shadow',
    shadowHover: 'theme-shadow-hover',
    success: 'emerald',
    warning: 'amber',
    danger: 'red',
  },
  dark: {
    name: 'Gelap Premium',
    variables: {
      '--theme-primary': '#64748b',
      '--theme-primary-hover': '#475569',
      '--theme-primary-light': '#f1f5f9',
      '--theme-primary-lighter': '#e2e8f0',
      '--theme-accent': '#475569',
      '--theme-accent-hover': '#334155',
      '--theme-text': '#475569',
      '--theme-text-dark': '#1e293b',
      '--theme-border': '#e2e8f0',
      '--theme-border-accent': '#64748b',
      '--theme-bg-light': '#f1f5f9',
      '--theme-bg-lighter': '#e2e8f0',
      '--theme-gradient-start': '#334155',
      '--theme-gradient-end': '#1e293b',
      '--theme-gradient-start-hover': '#1e293b',
      '--theme-gradient-end-hover': '#0f172a',
      '--theme-shadow': 'rgba(100, 116, 139, 0.08)',
      '--theme-shadow-hover': 'rgba(100, 116, 139, 0.15)',
    },
    primary: 'theme-primary',
    accent: 'theme-accent',
    accentHover: 'theme-accent-hover',
    light: 'theme-light',
    lighter: 'theme-lighter',
    text: 'theme-text',
    textDark: 'theme-text-dark',
    border: 'theme-border',
    borderAccent: 'theme-border-accent',
    bgLight: 'theme-bg-light',
    bgLighter: 'theme-bg-lighter',
    sidebar: 'from-theme-gradient-start to-theme-gradient-end',
    button: 'bg-gradient-to-r from-theme-gradient-start to-theme-gradient-end hover:from-theme-gradient-start-hover hover:to-theme-gradient-end-hover text-white shadow-sm shadow-theme-shadow',
    cardHeader: 'from-theme-gradient-start to-theme-gradient-end',
    shadow: 'theme-shadow',
    shadowHover: 'theme-shadow-hover',
    success: 'emerald',
    warning: 'amber',
    danger: 'red',
  },
};

export const getThemeClasses = (themeName) => {
  return themes[themeName] || themes.blue;
};

export const getThemeClass = (themeName, property) => {
  const theme = themes[themeName] || themes.blue;
  return theme[property] || '';
};
